### PR TITLE
Fix range formatting handling initial indentation

### LINKED ISSUE #264: Range formatting always adds indention when the range has initial indention
Perform range formatting on the following code and it works well.

```r
data <- dbQuery(
  con,
  "select name, group, max(update_time) as max_time
     from users
     where date = 20200525
     group by group"
)
```

However, it does not work well when the selection has initial indention like the following:

```r
fun <- function(x, y) {
  data <- dbQuery(
    con,
    "select name, group, max(update_time) as max_time
     from users
     where date = 20200525
     group by group"
  )
}
```

image

Once:

```r
fun <- function(x, y) {
  data <- dbQuery(
    con,
    "select name, group, max(update_time) as max_time
       from users
       where date = 20200525
       group by group"
  )
}
```

Twice:

```r
fun <- function(x, y) {
  data <- dbQuery(
    con,
    "select name, group, max(update_time) as max_time
         from users
         where date = 20200525
         group by group"
  )
}
```

More times:

```r
fun <- function(x, y) {
  data <- dbQuery(
    con,
    "select name, group, max(update_time) as max_time
               from users
               where date = 20200525
               group by group"
  )
}
```

This is particular annoying if on-type-formatting triggers range formatting inside the function like above.

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #264.

If the selection range has non-zero indentation, then a `apply_initial_indention` function injected to the formatting styles so that the top level expressions get the indentation.

For example, to format the code inside the the following function

```r
my_fun <- function() {
  data <- query(
    con ,
    "select name, group, max(update_time) as max_time
from users
where date = ?date
group by group",
date = 20200601
  )
x = 2
y = 3  
}
```

the code will be enclosed inside `{ ... } ` and then `apply_initial_indention` will apply the indention to all top-level expressions of the selection, then the curly braces are droped to get the formatted text.

The result is like 

```r
my_fun <- function() {
  data <- query(
    con,
    "select name, group, max(update_time) as max_time
from users
where date = ?date
group by group",
    date = 20200601
  )
  x = 2
  y = 3
}
```

### CODE REVIEW

File: R/formatting.R [hunk 1]
```diff
@@ -106,7 +122,7 @@ range_formatting_reply <- function(id, uri, document, range, options) {
     }
 
     selection <- document$content[(row1:row2) + 1]
-    indentation <- stringi::stri_extract_first_regex(selection[1], "^\\s*")
+    indentation <- nchar(stringi::stri_extract_first_regex(selection[1], "^\\s*"))
     new_text <- style_text(selection, style, indentation = indentation)
```
Comment (randy3k) [inline R/formatting.R:126]: it doesn't work with tabs unfortunately. Though it seems that styler doesn't support tabs https://github.com/r-lib/styler/issues/347

Comment (renkun-ken) [reply R/formatting.R:126]: Yes, it does not support tabs. So I just ignore this case unless somebody complains.
