### PR TITLE
Use internal `get_help` instead of repr

### LINKED ISSUE #468: Documentation not working with R 4.1.1
Looks like an upstream issue of `repr`:

```
[2021-08-12 13:16:43.195] internal error: Error: argument must be coercible to non-negative integer
Call: seq_len(head.end.idx)
Stack trace:
1: repr_help_files_with_topic_generic(obj, Rd2HTML)
2: repr_html.help_files_with_topic(hfile)
3: repr::repr_html(hfile)
4: workspace$get_help(token_result$token, token_result$package)
5: hover_reply(id, uri, self$workspace, document, point)
6: self$deliver(hover_reply(id, uri, self$workspace, document, point))
7: dispatch(self, id, params)

[2021-08-12 13:16:43.199] deliver:  ["Response", "Response", "Message", "R6"]

[Error - 1:16:43 PM] Request textDocument/hover failed.
  Message: Error: argument must be coercible to non-negative integer
Call: seq_len(head.end.idx)
Stack trace:
1: repr_help_files_with_topic_generic(obj, Rd2HTML)
2: repr_html.help_files_with_topic(hfile)
3: repr::repr_html(hfile)
4: workspace$get_help(token_result$token, token_result$package)
5: hover_reply(id, uri, self$workspace, document, point)
6: self$deliver(hover_reply(id, uri, self$workspace, document, point))
7: dispatch(self, id, params)
```

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #468 

This PR implements an internal `get_help()` to produce HTML or text from Rd. Then, repr is no longer imported.

### CODE REVIEW

File: R/workspace.R [hunk 1]
```diff
@@ -157,7 +157,7 @@ Workspace <- R6::R6Class("Workspace",
                     if (lsp_settings$get("rich_documentation") &&
                             requireNamespace("rmarkdown", quietly = TRUE) &&
                             rmarkdown::pandoc_available()) {
-                        html <- enc2utf8(repr::repr_html(hfile))
+                        html <- get_help(hfile, "html")
```
Comment (randy3k) [inline R/workspace.R:160]: To play safe, it may be better to keep `enc2utf8` around.

Comment (renkun-ken) [reply R/workspace.R:160]: Sure

Comment (renkun-ken) [reply R/workspace.R:160]: Done in `get_help()`.

**Review by randy3k — APPROVED** [review]
