### PR TITLE
Fix formatting empty file

### LINKED ISSUE #53: Formatting empty document causes internal error
Formatting an empty document will cause an internal error:

```
internal error:  list(message = "attempt to select less than one element in integerOneIndex", call = document[[ndoc]])

[Error - 10:51:54 AM] Request textDocument/formatting failed.
  Message: attempt to select less than one element in integerOneIndex document[[ndoc]]

  Code: -32603 
```

It's caused by `formatting_reply` where document length is assumed to be non-zero. I'll file a PR quickly for this.

### PR DESCRIPTION
**Pull request by renkun-ken**
This PR fixes #53.

### CODE REVIEW

File: R/formatting.R [hunk 1]
```diff
@@ -50,7 +50,7 @@ formatting_reply <- function(id, uri, document, options) {
     ndoc <- length(document)
     range <- range(
         start = position(line = 0, character = 0),
-        end = position(line = ndoc - 1, character = nchar(document[[ndoc]]))
+        end = position(line = max(0, ndoc - 1), character = nchar(document[ndoc]))
```
Comment (randy3k) [inline R/formatting.R]: It should really be `document[[ndoc]]`.

Comment (renkun-ken) [reply R/formatting.R]: `documentp[[ndoc]]` is the place where error occurs since `ndoc = 0` for empty document and `document[[0]]` produces error.

Comment (renkun-ken) [reply R/formatting.R]: Sorry for the mistake.
