### PR TITLE
Always use content in diagnose_file

### LINKED ISSUE #222: Diagnostics not working for one-line document
If the document is untitled, then `lintr::lint` will produce an error since it does not support one-line text without `\n` ending.

If the document is not untitled, then diagnostics is not performed with the latest content of document updated via text sync.

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #222 

This PR always uses `content` in `diagnose_file` and fixes one-line content so that it could correctly handle one-line content and untitled document.

We should avoid reading the file from the path of URI as long as we could get the content, or otherwise the unsaved or untitled document cannot be handled correctly.

### CODE REVIEW

File: R/diagnostics.R [hunk 1]
```diff
@@ -74,24 +74,20 @@ diagnose_file <- function(uri, content) {
...
+            return(list())
         }
-        # use inline data
-        text <- paste0(content, collapse = "\n")
-        diagnostics <- lapply(
-            lintr::lint(text, linters = linters), diagnostic_from_lint, content = content)
+    }
 
+    if (length(content) <= 1) {
+        content <- c(content, "")
```
Comment (randy3k) [inline R/diagnostics.R]: smarter than what I did.

Comment (renkun-ken) [reply R/diagnostics.R]: Is it possible that we get `length(content) == 0`? In this case, `paste0("", collapose = "\n")` stills returns `""`.

Comment (randy3k) [reply R/diagnostics.R]: It seems that content is always a string, and cannot be NULL.

Comment (renkun-ken) [reply R/diagnostics.R]: Yes, just refined to return early for all cases with unqualified content.
